# Generated by Django 5.1.6 on 2025-05-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_article_author_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='entry',
            field=models.TextField(null='TRUE'),
            preserve_default='TRUE',
        ),
        migrations.AddField(
            model_name='article',
            name='header_image',
            field=models.ImageField(null='TRUE', upload_to=''),
            preserve_default='TRUE',
        ),
        migrations.AddField(
            model_name='comment',
            name='entry',
            field=models.TextField(null='TRUE'),
            preserve_default='TRUE',
        ),
    ]
