# Generated by Django 5.1.6 on 2025-05-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_article_entry_article_header_image_comment_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='entry',
            field=models.TextField(null='FALSE'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='entry',
            field=models.TextField(null='FALSE'),
        ),
    ]
