# Generated by Django 5.1.6 on 2025-05-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_alter_article_entry_alter_comment_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='entry',
            field=models.TextField(null='TRUE'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='entry',
            field=models.TextField(null='TRUE'),
        ),
    ]
