# Generated by Django 5.1.6 on 2025-05-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_alter_article_entry_alter_comment_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header_image',
            field=models.ImageField(null='TRUE', upload_to='images/'),
        ),
    ]
