# Generated by Django 5.1.6 on 2025-05-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_alter_comment_article_alter_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
