# Generated by Django 5.1.6 on 2025-05-12 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='wiki.articlecategory'),
        ),
        migrations.AlterField(
            model_name='article',
            name='entry',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='header_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='entry',
            field=models.TextField(),
        ),
    ]
