# Generated by Django 5.1.6 on 2025-05-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0013_articlecategory_description_alter_article_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='description',
            field=models.TextField(),
        ),
    ]
