# Generated by Django 5.1.6 on 2025-05-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0014_alter_articlecategory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
