# Generated by Django 5.1.7 on 2025-05-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_author_article_header_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header_img',
            field=models.ImageField(blank=True, null=True, upload_to='blog/headers/'),
        ),
    ]
