# Generated by Django 5.1.6 on 2025-04-22 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_remove_commission_people_required_commission_status_and_more'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='user_management.profile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='commissions.job')),
            ],
            options={
                'ordering': [models.Case(models.When(status='Pending', then=models.Value(0)), models.When(status='Accepted', then=models.Value(1)), models.When(status='Rejected', then=models.Value(2)), output_field=models.IntegerField()), '-applied_on'],
            },
        ),
    ]
