# Generated by Django 5.1.6 on 2025-05-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_commission_poster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': [models.Case(models.When(status='Open', then=models.Value(0)), models.When(status='Full', then=models.Value(1)), models.When(status='Completed', then=models.Value(2)), models.When(status='Discontinued', then=models.Value(3)), output_field=models.IntegerField()), 'created_on']},
        ),
    ]
