# Generated by Django 5.1.6 on 2025-05-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0006_alter_commission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': [models.Case(models.When(status='Full', then=models.Value(0)), models.When(status='Open', then=models.Value(1)), output_field=models.IntegerField()), '-manpower_required', 'role']},
        ),
    ]
